#!/bin/bash

echo "usage: /vybe:[command] [options] ... [args] ..."
echo ""
echo "Vybe Framework - Spec-driven Agile Development"
echo "Commands:"
echo "  template    Import and analyze external templates"
echo "  init        Initialize project with staged outcome roadmap"
echo "  backlog     Strategic backlog management with member coordination"  
echo "  plan        Create detailed feature specifications"
echo "  execute     Execute tasks with full context and member coordination"
echo "  status      Progress tracking and member assignments"
echo "  audit       Quality assurance and code-reality analysis"
echo "  release     Mark outcome stage complete and advance"
echo "  discuss     Natural language assistant with smart audit routing"
echo "  help        Show this help message"
echo ""
echo "Options:"
echo "  --auto      Automated mode (AI makes decisions without confirmation)"
echo "  --role=dev-N Execute as specific team member (dev-1 to dev-5)"
echo "  --template=name Apply template-driven architectural DNA"
echo ""
echo "Examples:"
echo "  /vybe:init \"My project description\""
echo "  /vybe:backlog init"
echo "  /vybe:plan user-auth \"User login system\""
echo "  /vybe:execute stage-1"
echo "  /vybe:status overall"
echo ""
echo "Environment:"
echo "  VYBE_MEMBER Set developer role (dev-1, dev-2, dev-3, dev-4, dev-5)"
echo ""
echo "Use '/vybe:[command] help' for detailed help on specific commands."
echo "Use '/vybe:discuss \"question\"' for interactive assistance."